[{"name": "test.test_number_stats.NumbesrStatsTest.test0a_main_ok", "status": "passed", "message": "", "passed": true, "points": [], "backtrace": []}, {"name": "test.test_number_stats.NumbesrStatsTest.test1_class_exists", "status": "failed", "message": "Your program should have a class called NumberStats", "passed": false, "points": ["8.number_stats_part1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 35, in test1_class_exists\n    self.fail(\"Your program should have a class called NumberStats\")\n"]}, {"name": "test.test_number_stats.NumbesrStatsTest.test2_constructor", "status": "failed", "message": "Calling constructor NumberStats()  threw an error: ", "passed": false, "points": ["8.number_stats_part1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 44, in test2_constructor\n    self.fail('Calling constructor NumberStats() ' +\n"]}, {"name": "test.test_number_stats.NumbesrStatsTest.test2b_test_methods", "status": "errored", "message": "EOF when reading a line", "passed": false, "points": ["8.number_stats_part1"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 49, in test2b_test_methods\n    from src.number_stats import NumberStats\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\src\\number_stats.py\", line 33, in <module>\n"]}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_test_average", "status": "errored", "message": "EOF when reading a line", "passed": false, "points": ["8.number_stats_part2"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 126, in test3_test_average\n    from src.number_stats import NumberStats\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\src\\number_stats.py\", line 23, in <module>\n    number = int(input(''))\n                 ^^^^^^^^^\n"]}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_test_count_numbers", "status": "passed", "message": "", "passed": true, "points": ["8.number_stats_part1"], "backtrace": []}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_test_empty_average", "status": "passed", "message": "", "passed": true, "points": ["8.number_stats_part2"], "backtrace": []}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_test_get_sum", "status": "passed", "message": "", "passed": true, "points": ["8.number_stats_part2"], "backtrace": []}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_test_input_get_sum_and_avg", "status": "failed", "message": "Running exercise src.number_stats failed. Please make sure that you can run your code.", "passed": false, "points": ["8.number_stats_part3"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 153, in test3_test_input_get_sum_and_avg\n    reload_module(self.module)\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\tmc\\utils.py\", line 42, in reload_module\n    raise module\n"]}, {"name": "test.test_number_stats.NumbesrStatsTest.test3_testaa_input_even_odd", "status": "failed", "message": "Running exercise src.number_stats failed. Please make sure that you can run your code.", "passed": false, "points": ["8.number_stats_part4"], "backtrace": ["  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\test\\test_number_stats.py\", line 171, in test3_testaa_input_even_odd\n    reload_module(self.module)\n", "  File \"C:\\Users\\squad\\AppData\\Local\\tmc\\vscode\\mooc-programming-24\\part08-12_number_stats\\tmc\\utils.py\", line 42, in reload_module\n    raise module\n"]}]